name: mt_gilead
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.4.0
  cloud_firestore: ^0.11.0+1
  firebase_auth: ^0.10.0+1
  firebase_storage: ^3.0.0
  shared_preferences: any
  flushbar: ^1.5.0
  flutter_carousel: ^0.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/a.jpg
    - assets/images/b.jpg
    - assets/images/c.jpg
    - assets/images/d.jpg
    - assets/images/f.jpg
    - assets/images/g.jpg
    - assets/images/h.jpg
    - assets/images/i.jpg
    - assets/images/j.jpg
    - assets/images/k.jpg
    - assets/images/l.jpg
    - assets/images/m.jpg
    - assets/images/n.jpg
    - assets/images/cp.jpg
    - assets/images/cop.jpg
    - assets/images/mtgilead.jpg
    - assets/images/hat.jpeg
    - assets/images/bd.jpg
    - assets/images/bishop.jpg
    - assets/images/yellowSale.jpg
    - assets/images/transform.jpg
    - assets/images/logo.jpg